kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prometheus-status.serviceAccountName" . }}
  labels:
    {{- include "prometheus-status.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["list"]